repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        files: ^mainV3D_no_robodk/.*\.py$
        args: [--fix]
      - id: ruff-format
        files: ^mainV3D_no_robodk/.*\.py$

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^mainV3D_no_robodk/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^mainV3D_no_robodk/.*\.py$
        additional_dependencies:
          - numpy>=1.20
